# info for run
code_root: null
# log to weights and biases
integrations:
  wandb:
    active: False
    project: "sketch2face"

iterator: iterator.cycle_wgan.Cycle_WGAN
model: models.style_transfer_model.Style_Transfer_Model
random_seed: 10
explanation: "Testing"
debug_log_level: True

## Iterator info ##
# specify the batchsize for training
batch_size: 1 #DO NOT CHANGE
# specify the length of training
# in either "num_epochs" or "num_steps" 
num_steps: 5000

model_config:
  min_channels: 32
  max_channels: 128
  in_channels: 3
  out_channels: 3
  in_size: &IN_SIZE 128
  num_classes: 5
  num_extra_conv: 0
  lin_layer_size: 0
  #block_activation: "relu" TO BE IMPLEMANTED
  #final_activation: "tanh" TO BE IMPLEMANTED
  batch_norm: False
  drop_rate: None
  bias: True

data:
  style_path: "C:\\Users\\user\\Desktop\\Zeug\\Style transfer\\data\\art\\selection"
  content_path: "C:\\Users\\user\\Desktop\\Zeug\\Style transfer\\data\\landscapes"
  validation_split: 0.1

  transforms:
    in_size: *IN_SIZE
    crop: 
      type: "center" #or random or max_random (yet to be implemented)
      size: 512
    mirror: True

optimizer:
  lr: 0.0001
  D_lr_factor: 1

losses:
  adv_weight: 1
  rec_weight: 1
  fp_cont_weight: 1
  fpt_style_weight: 1
  fpt_margin: 0
  fpd_weight: 1